FROM hexpm/elixir:1.15.8-erlang-25.2.3-debian-bookworm-20240722

RUN apt-get update && \
    apt-get install -y \
    postgresql-client inotify-tools

RUN DEBIAN_FRONTEND=noninteractive apt-get install -y \
    build-essential xorg libssl-dev libxrender-dev git wget gdebi xvfb \
    wkhtmltopdf \
    pandoc \
    texlive-fonts-recommended \
    texlive-plain-generic \
    texlive-latex-extra \
    texlive-xetex

RUN echo "xvfb-run -a -s \"-screen 0 640x480x16\" wkhtmltopdf \"\$@\"" >/usr/local/bin/wkhtmltopdf-wrapper && chmod +x /usr/local/bin/wkhtmltopdf-wrapper

COPY ./entrypoint_dev.sh /app/
# COPY ./entrypoint_dev.sh /app/entrypoint.sh

WORKDIR /app
COPY config /app/config
COPY lib /app/lib
COPY mix.exs mix.lock /app/
COPY priv priv
COPY assets assets

ARG SECRET_KEY_BASE

# only for dev
COPY ./entrypoint_dev.sh /app/

RUN mix local.hex --force && \
    mix local.rebar --force && \
    mix deps.get

RUN mix do compile

EXPOSE 4000
CMD ["bash", "/app/entrypoint_dev.sh"]
