defmodule WraftDoc.Workflows.Adaptors.TemplateAdaptor do
  @moduledoc """
  Template generation adaptor.

  Generates mock contract documents from templates.

  Configuration:
  - template_name: String - name of the template to use (e.g., "Template 1", "Template 2")
  - template_type: String (optional) - type of document (default: "contract")

  Example:
  config: %{"template_name" => "Template 1", "template_type" => "contract"}
  input_data: %{"age" => 30, "name" => "John Doe"}
  output: {:ok, %{template: "Template 1", content: "...", generated_at: ~U[...]}}
  """

  @behaviour WraftDoc.Workflows.Adaptors.Adaptor

  require Logger

  @impl true
  def execute(config, input_data, _credentials) do
    template_name = Map.get(config, "template_name", "Default Template")
    template_type = Map.get(config, "template_type", "contract")

    # Extract user info from input data
    name = Map.get(input_data, "name") || Map.get(input_data, :name) || "User"
    age = Map.get(input_data, "age") || Map.get(input_data, :age)

    # Generate mock contract content
    content = generate_mock_content(template_name, template_type, name, age)

    Logger.info("[TemplateAdaptor] Generated #{template_type} from #{template_name} for #{name}")

    {:ok,
     %{
       template: template_name,
       template_type: template_type,
       content: content,
       generated_at: DateTime.utc_now(),
       metadata: %{
         name: name,
         age: age,
         word_count: String.length(content)
       }
     }}
  end

  @impl true
  def validate_config(config) do
    cond do
      !Map.has_key?(config, "template_name") -> {:error, "template_name is required"}
      !is_binary(config["template_name"]) -> {:error, "template_name must be a string"}
      true -> :ok
    end
  end

  defp generate_mock_content(template_name, template_type, name, age) do
    """
    ═══════════════════════════════════════════════════════════════
    #{String.upcase(template_type)} AGREEMENT - #{template_name}
    ═══════════════════════════════════════════════════════════════

    Generated: #{DateTime.to_string(DateTime.utc_now())}

    PARTIES:
    This agreement is made between:

    Party A: #{name}#{if age, do: " (Age: #{age})", else: ""}
    Party B: ACME Corporation

    TERMS AND CONDITIONS:

    #{generate_terms(template_name, age)}

    SIGNATURES:

    _____________________          _____________________
    #{name}                         ACME Representative
    Date: _______________          Date: _______________

    ═══════════════════════════════════════════════════════════════
    Generated by Wraft Workflow Engine - #{template_name}
    Document ID: #{generate_doc_id()}
    ═══════════════════════════════════════════════════════════════
    """
  end

  defp generate_terms("Template 1", age) do
    """
    1. EMPLOYMENT TERMS (Senior Level - Age #{age || "N/A"})
       - This is a senior-level employment contract
       - Position: Senior Consultant
       - Salary: $120,000 per annum
       - Benefits: Full health coverage, retirement plan, stock options
       - Vacation: 25 days per year

    2. RESPONSIBILITIES
       - Lead project teams and mentor junior staff
       - Strategic planning and client relationship management
       - Annual performance reviews and goal setting

    3. TERM
       - Initial term: 3 years with option to extend
       - Notice period: 90 days
    """
  end

  defp generate_terms("Template 2", age) do
    """
    1. EMPLOYMENT TERMS (Entry Level - Age #{age || "N/A"})
       - This is an entry-level employment contract
       - Position: Junior Consultant
       - Salary: $65,000 per annum
       - Benefits: Health coverage, 401(k) matching
       - Vacation: 15 days per year

    2. RESPONSIBILITIES
       - Work under supervision of senior consultants
       - Learn company processes and best practices
       - Participate in training and development programs

    3. TERM
       - Initial term: 1 year with option to extend
       - Notice period: 30 days
    """
  end

  defp generate_terms(template_name, _age) do
    """
    1. GENERAL TERMS
       - This document was generated using #{template_name}
       - Standard terms and conditions apply
       - Subject to applicable laws and regulations

    2. OBLIGATIONS
       - Both parties agree to act in good faith
       - Confidentiality must be maintained
       - Disputes to be resolved through arbitration

    3. TERM
       - As mutually agreed upon
       - Subject to renewal or termination clauses
    """
  end

  defp generate_doc_id do
    Base.encode16(:crypto.strong_rand_bytes(8), case: :lower)
  end
end
