apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: wraft-docs-server
  annotations:
    ingress.kubernetes.io/ssl-redirect: "false"
spec:
  rules:
    - http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: wraft-docs-server
                port:
                  number: 9091
